services:
  app-dev:
    build:
      context: .
    container_name: ecommerce-app-dev
    env_file:
      - .env.template
      - .env.dev.template
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DEV_DB_URL: jdbc:postgresql://host.docker.internal:5432/ecommerce_dev
      DEV_DB_USERNAME: postgres
      DEV_DB_PASSWORD: postgres
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
    ports:
      - "9005:9005"
    depends_on:
      - redis-cache

  redis-cache:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"

  adminer:
    image: adminer:4
    container_name: ecommerce-adminer
    ports:
      - "8080:8080"