spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}
app.cors.allowed-origins=${PROD_CORS_ALLOWED_ORIGINS}
app.jwt.secret=${PROD_JWT_SECRET}
